apiVersion: apps/v1 
kind: Deployment
metadata:
  name: object-detection-inf_deploy 
  labels:
    app: obj-detection-inf 
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: obj-detection-inf
  template:
    metadata:
      name: object-detection-inf-pod
      labels:
        app: obj-detection-inf
    spec:
      containers:
        - name: object-detection-inf-container 
          image: aadetola/model_api_image:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          
