apiVersion: apps/v1 
kind: Deployment
metadata:
  name: object-detection-inf-deploy 
  labels:
    app: obj-detection-inf 
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: obj-detection-inf
  template:
    metadata:
      name: object-detection-inf-pod
      labels:
        app: obj-detection-inf
    spec:
      containers:
        - name: object-detection-inf-container 
          image: aadetola/model_api_image_v2:latest
          # shell -c evaluates a string as shell input
          #command: [ "sh", "-c"]
          #loop forever, outputting "yo" every 5 seconds
          #args: ["while true; do echo 'yo' && sleep 5; done;"]
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          
          #kubectl exec -it pod/name_of_pod -- sh
