apiVersion: v1 
kind: Service
metadata:
  name: object_detection_inf_service 
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 31007
      targetPort: 80
  selector:
    app: obj_detection_inf 
    
    