apiVersion: v1 
kind: Service
metadata:
  name: object-detection-inf-service 
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 31007
      targetPort: 80
  selector:
    app: obj-detection-inf 
    
    
